gas_sensor_sim_node:
  ros__parameters:
    enable_gas: true
    debug_gas: true
    pose_topic: /rtabmap/localization_pose
    odom_topic: /odom
    gas_topic: /gas/concentration
    gas_publish_rate_hz: 5.0
    gas_pose_fallback_mode: true
    fallback_x: 0.0
    fallback_y: 0.0
    gas_source_x: 2.0
    gas_source_y: 2.0
    gas_sigma: 1.5
    gas_amplitude: 1.0
    background: 0.02
